name: Reusable Trivy

on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: "1"
          