name: Feature Pipeline

on:
  push:
    branches:
      - "feature/**"

jobs:

  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/reusable-test.yml

  sonarcloud:
    name: SonarCloud
    needs: test
    uses: ./.github/workflows/reusable-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk:
    name: Snyk
    needs: build
    uses: ./.github/workflows/reusable-snyk.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
 