name: Feature Pipeline

on:
  push:
    branches:
      - "feature/**"

jobs:

  build:
    name: Build
    uses: ./.github/workflows/reusable/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/reusable/test.yml

  sonarcloud:
    needs: build
    uses: ./.github/workflows/reusable/sonarcloud.yml
    secrets: inherit

  snyk:
    needs: build
    uses: ./.github/workflows/reusable/snyk.yml
    secrets: inherit

  trivy:
    needs: build
    uses: ./.github/workflows/reusable/trivy.yml